[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"